import type { Wrestler } from "./types";

export const top200DraftPool: Wrestler[] = [
  {
    "id": "aew-aew-kenny-omega",
    "name": "Kenny Omega",
    "popularity": 99,
    "momentum": 93,
    "fatigue": 23,
    "morale": 62,
    "ringSkill": 97,
    "promoSkill": 99,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-rhea-ripley",
    "name": "Rhea Ripley",
    "popularity": 99,
    "momentum": 95,
    "fatigue": 10,
    "morale": 70,
    "ringSkill": 98,
    "promoSkill": 99,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-roman-reigns",
    "name": "Roman Reigns",
    "popularity": 99,
    "momentum": 93,
    "fatigue": 11,
    "morale": 72,
    "ringSkill": 96,
    "promoSkill": 99,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-cody-rhodes",
    "name": "Cody Rhodes",
    "popularity": 99,
    "momentum": 93,
    "fatigue": 11,
    "morale": 72,
    "ringSkill": 96,
    "promoSkill": 99,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-becky-lynch",
    "name": "Becky Lynch",
    "popularity": 98,
    "momentum": 93,
    "fatigue": 17,
    "morale": 78,
    "ringSkill": 96,
    "promoSkill": 93,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kazuchika-okada",
    "name": "Kazuchika Okada",
    "popularity": 96,
    "momentum": 91,
    "fatigue": 22,
    "morale": 62,
    "ringSkill": 93,
    "promoSkill": 97,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-seth-rollins",
    "name": "Seth Rollins",
    "popularity": 99,
    "momentum": 92,
    "fatigue": 14,
    "morale": 66,
    "ringSkill": 94,
    "promoSkill": 99,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-chris-jericho",
    "name": "Chris Jericho",
    "popularity": 99,
    "momentum": 92,
    "fatigue": 14,
    "morale": 66,
    "ringSkill": 94,
    "promoSkill": 99,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-cm-punk",
    "name": "CM Punk",
    "popularity": 99,
    "momentum": 93,
    "fatigue": 14,
    "morale": 64,
    "ringSkill": 92,
    "promoSkill": 91,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-bianca-belair",
    "name": "Bianca Belair",
    "popularity": 98,
    "momentum": 93,
    "fatigue": 17,
    "morale": 78,
    "ringSkill": 96,
    "promoSkill": 93,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-iyo-sky",
    "name": "IYO SKY",
    "popularity": 99,
    "momentum": 93,
    "fatigue": 14,
    "morale": 72,
    "ringSkill": 97,
    "promoSkill": 97,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-gunther",
    "name": "Gunther",
    "popularity": 99,
    "momentum": 94,
    "fatigue": 24,
    "morale": 78,
    "ringSkill": 95,
    "promoSkill": 99,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-drew-mcintyre",
    "name": "Drew McIntyre",
    "popularity": 99,
    "momentum": 93,
    "fatigue": 13,
    "morale": 74,
    "ringSkill": 95,
    "promoSkill": 98,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-randy-orton",
    "name": "Randy Orton",
    "popularity": 99,
    "momentum": 93,
    "fatigue": 16,
    "morale": 68,
    "ringSkill": 96,
    "promoSkill": 96,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-liv-morgan",
    "name": "Liv Morgan",
    "popularity": 94,
    "momentum": 91,
    "fatigue": 10,
    "morale": 72,
    "ringSkill": 94,
    "promoSkill": 98,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-will-ospreay",
    "name": "Will Ospreay",
    "popularity": 94,
    "momentum": 87,
    "fatigue": 21,
    "morale": 65,
    "ringSkill": 94,
    "promoSkill": 97,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-stephanie-vaquer",
    "name": "Stephanie Vaquer",
    "popularity": 94,
    "momentum": 91,
    "fatigue": 10,
    "morale": 72,
    "ringSkill": 94,
    "promoSkill": 98,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-naomi",
    "name": "Naomi",
    "popularity": 94,
    "momentum": 91,
    "fatigue": 10,
    "morale": 72,
    "ringSkill": 94,
    "promoSkill": 98,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mercedes-mon",
    "name": "Mercedes Moné",
    "popularity": 94,
    "momentum": 91,
    "fatigue": 10,
    "morale": 72,
    "ringSkill": 94,
    "promoSkill": 98,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-asuka",
    "name": "Asuka",
    "popularity": 98,
    "momentum": 90,
    "fatigue": 25,
    "morale": 70,
    "ringSkill": 92,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-bron-breakker",
    "name": "Bron Breakker",
    "popularity": 93,
    "momentum": 91,
    "fatigue": 20,
    "morale": 70,
    "ringSkill": 92,
    "promoSkill": 91,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-jon-moxley",
    "name": "Jon Moxley",
    "popularity": 94,
    "momentum": 89,
    "fatigue": 25,
    "morale": 68,
    "ringSkill": 91,
    "promoSkill": 93,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-charlotte-flair",
    "name": "Charlotte Flair",
    "popularity": 95,
    "momentum": 88,
    "fatigue": 14,
    "morale": 71,
    "ringSkill": 94,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-swerve-strickland",
    "name": "Swerve Strickland",
    "popularity": 93,
    "momentum": 89,
    "fatigue": 10,
    "morale": 63,
    "ringSkill": 91,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-jade-cargill",
    "name": "Jade Cargill",
    "popularity": 95,
    "momentum": 91,
    "fatigue": 12,
    "morale": 80,
    "ringSkill": 88,
    "promoSkill": 87,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-willow-nightingale",
    "name": "Willow Nightingale",
    "popularity": 89,
    "momentum": 84,
    "fatigue": 21,
    "morale": 71,
    "ringSkill": 89,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-thekla",
    "name": "Thekla",
    "popularity": 89,
    "momentum": 84,
    "fatigue": 21,
    "morale": 71,
    "ringSkill": 89,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-tiffany-stratton",
    "name": "Tiffany Stratton",
    "popularity": 90,
    "momentum": 89,
    "fatigue": 20,
    "morale": 70,
    "ringSkill": 91,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-jay-white",
    "name": "Jay White",
    "popularity": 93,
    "momentum": 89,
    "fatigue": 40,
    "morale": 63,
    "ringSkill": 91,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mjf",
    "name": "MJF",
    "popularity": 92,
    "momentum": 86,
    "fatigue": 21,
    "morale": 66,
    "ringSkill": 91,
    "promoSkill": 97,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-jacob-fatu",
    "name": "Jacob Fatu",
    "popularity": 91,
    "momentum": 85,
    "fatigue": 19,
    "morale": 63,
    "ringSkill": 87,
    "promoSkill": 83,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-jey-uso",
    "name": "Jey Uso",
    "popularity": 91,
    "momentum": 89,
    "fatigue": 19,
    "morale": 72,
    "ringSkill": 86,
    "promoSkill": 87,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-logan-paul",
    "name": "Logan Paul",
    "popularity": 93,
    "momentum": 86,
    "fatigue": 20,
    "morale": 64,
    "ringSkill": 88,
    "promoSkill": 95,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-eddie-kingston",
    "name": "Eddie Kingston",
    "popularity": 89,
    "momentum": 89,
    "fatigue": 11,
    "morale": 75,
    "ringSkill": 93,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-pac",
    "name": "PAC",
    "popularity": 91,
    "momentum": 87,
    "fatigue": 15,
    "morale": 73,
    "ringSkill": 89,
    "promoSkill": 96,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-adam-copeland",
    "name": "Adam Copeland",
    "popularity": 91,
    "momentum": 87,
    "fatigue": 15,
    "morale": 73,
    "ringSkill": 89,
    "promoSkill": 96,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-bayley",
    "name": "Bayley",
    "popularity": 86,
    "momentum": 85,
    "fatigue": 12,
    "morale": 79,
    "ringSkill": 91,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-samoa-joe",
    "name": "Samoa Joe",
    "popularity": 89,
    "momentum": 87,
    "fatigue": 24,
    "morale": 66,
    "ringSkill": 88,
    "promoSkill": 95,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-orange-cassidy",
    "name": "Orange Cassidy",
    "popularity": 87,
    "momentum": 81,
    "fatigue": 13,
    "morale": 64,
    "ringSkill": 86,
    "promoSkill": 81,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kevin-knight",
    "name": "Kevin Knight",
    "popularity": 90,
    "momentum": 87,
    "fatigue": 18,
    "morale": 79,
    "ringSkill": 84,
    "promoSkill": 86,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-dax-harwood",
    "name": "Dax Harwood",
    "popularity": 90,
    "momentum": 87,
    "fatigue": 18,
    "morale": 79,
    "ringSkill": 84,
    "promoSkill": 86,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-megan-bayne",
    "name": "Megan Bayne",
    "popularity": 89,
    "momentum": 86,
    "fatigue": 25,
    "morale": 79,
    "ringSkill": 85,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-sami-zayn",
    "name": "Sami Zayn",
    "popularity": 90,
    "momentum": 88,
    "fatigue": 13,
    "morale": 79,
    "ringSkill": 87,
    "promoSkill": 93,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-la-knight",
    "name": "LA Knight",
    "popularity": 90,
    "momentum": 88,
    "fatigue": 13,
    "morale": 79,
    "ringSkill": 87,
    "promoSkill": 93,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-nia-jax",
    "name": "Nia Jax",
    "popularity": 88,
    "momentum": 87,
    "fatigue": 19,
    "morale": 72,
    "ringSkill": 88,
    "promoSkill": 81,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-bronson-reed",
    "name": "Bronson Reed",
    "popularity": 90,
    "momentum": 86,
    "fatigue": 25,
    "morale": 75,
    "ringSkill": 88,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-bobby-lashley",
    "name": "Bobby Lashley",
    "popularity": 90,
    "momentum": 86,
    "fatigue": 25,
    "morale": 75,
    "ringSkill": 88,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-kevin-owens",
    "name": "Kevin Owens",
    "popularity": 88,
    "momentum": 82,
    "fatigue": 19,
    "morale": 63,
    "ringSkill": 83,
    "promoSkill": 87,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kyle-o-reilly",
    "name": "Kyle O'Reilly",
    "popularity": 85,
    "momentum": 84,
    "fatigue": 14,
    "morale": 70,
    "ringSkill": 86,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-cash-wheeler",
    "name": "Cash Wheeler",
    "popularity": 85,
    "momentum": 84,
    "fatigue": 14,
    "morale": 70,
    "ringSkill": 86,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-damian-priest",
    "name": "Damian Priest",
    "popularity": 90,
    "momentum": 88,
    "fatigue": 14,
    "morale": 76,
    "ringSkill": 86,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-raquel-rodriguez",
    "name": "Raquel Rodriguez",
    "popularity": 89,
    "momentum": 84,
    "fatigue": 25,
    "morale": 69,
    "ringSkill": 86,
    "promoSkill": 82,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-nattie",
    "name": "Nattie",
    "popularity": 89,
    "momentum": 84,
    "fatigue": 25,
    "morale": 69,
    "ringSkill": 86,
    "promoSkill": 82,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-giulia",
    "name": "Giulia",
    "popularity": 89,
    "momentum": 84,
    "fatigue": 25,
    "morale": 69,
    "ringSkill": 86,
    "promoSkill": 82,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-roderick-strong",
    "name": "Roderick Strong",
    "popularity": 88,
    "momentum": 85,
    "fatigue": 19,
    "morale": 63,
    "ringSkill": 85,
    "promoSkill": 84,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-ricochet",
    "name": "Ricochet",
    "popularity": 86,
    "momentum": 80,
    "fatigue": 18,
    "morale": 61,
    "ringSkill": 86,
    "promoSkill": 80,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-darby-allin",
    "name": "Darby Allin",
    "popularity": 87,
    "momentum": 86,
    "fatigue": 22,
    "morale": 64,
    "ringSkill": 82,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-finn-b-lor",
    "name": "Finn Bálor",
    "popularity": 86,
    "momentum": 85,
    "fatigue": 22,
    "morale": 80,
    "ringSkill": 85,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-sheamus",
    "name": "Sheamus",
    "popularity": 86,
    "momentum": 85,
    "fatigue": 11,
    "morale": 65,
    "ringSkill": 88,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-dominik-mysterio",
    "name": "Dominik Mysterio",
    "popularity": 87,
    "momentum": 85,
    "fatigue": 12,
    "morale": 60,
    "ringSkill": 85,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mark-davis",
    "name": "Mark Davis",
    "popularity": 84,
    "momentum": 78,
    "fatigue": 21,
    "morale": 64,
    "ringSkill": 84,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-alexa-bliss",
    "name": "Alexa Bliss",
    "popularity": 88,
    "momentum": 82,
    "fatigue": 20,
    "morale": 63,
    "ringSkill": 86,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-shinsuke-nakamura",
    "name": "Shinsuke Nakamura",
    "popularity": 88,
    "momentum": 83,
    "fatigue": 22,
    "morale": 80,
    "ringSkill": 84,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-jimmy-uso",
    "name": "Jimmy Uso",
    "popularity": 88,
    "momentum": 83,
    "fatigue": 22,
    "morale": 80,
    "ringSkill": 84,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-ilja-dragunov",
    "name": "Ilja Dragunov",
    "popularity": 85,
    "momentum": 83,
    "fatigue": 10,
    "morale": 78,
    "ringSkill": 83,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-chelsea-green",
    "name": "Chelsea Green",
    "popularity": 87,
    "momentum": 86,
    "fatigue": 17,
    "morale": 68,
    "ringSkill": 85,
    "promoSkill": 94,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-roxanne-perez",
    "name": "Roxanne Perez",
    "popularity": 85,
    "momentum": 80,
    "fatigue": 19,
    "morale": 61,
    "ringSkill": 85,
    "promoSkill": 83,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-tommaso-ciampa",
    "name": "Tommaso Ciampa",
    "popularity": 86,
    "momentum": 86,
    "fatigue": 16,
    "morale": 69,
    "ringSkill": 82,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mark-briscoe",
    "name": "Mark Briscoe",
    "popularity": 86,
    "momentum": 86,
    "fatigue": 16,
    "morale": 69,
    "ringSkill": 82,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-penta",
    "name": "Penta",
    "popularity": 85,
    "momentum": 82,
    "fatigue": 20,
    "morale": 64,
    "ringSkill": 84,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-christian-cage",
    "name": "Christian Cage",
    "popularity": 87,
    "momentum": 87,
    "fatigue": 15,
    "morale": 78,
    "ringSkill": 85,
    "promoSkill": 82,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-dr-britt-baker-d-m-d",
    "name": "Dr. Britt Baker, D.M.D.",
    "popularity": 85,
    "momentum": 80,
    "fatigue": 49,
    "morale": 61,
    "ringSkill": 85,
    "promoSkill": 83,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-solo-sikoa",
    "name": "Solo Sikoa",
    "popularity": 84,
    "momentum": 83,
    "fatigue": 17,
    "morale": 77,
    "ringSkill": 86,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-original-el-grande-americano",
    "name": "Original El Grande Americano",
    "popularity": 84,
    "momentum": 83,
    "fatigue": 17,
    "morale": 77,
    "ringSkill": 86,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-nick-jackson",
    "name": "Nick Jackson",
    "popularity": 84,
    "momentum": 83,
    "fatigue": 17,
    "morale": 77,
    "ringSkill": 86,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-matt-jackson",
    "name": "Matt Jackson",
    "popularity": 84,
    "momentum": 83,
    "fatigue": 17,
    "morale": 77,
    "ringSkill": 86,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-el-grande-americano",
    "name": "El Grande Americano",
    "popularity": 84,
    "momentum": 83,
    "fatigue": 17,
    "morale": 77,
    "ringSkill": 86,
    "promoSkill": 89,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-timeless-toni-storm",
    "name": "\"Timeless\" Toni Storm",
    "popularity": 86,
    "momentum": 79,
    "fatigue": 50,
    "morale": 60,
    "ringSkill": 83,
    "promoSkill": 95,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-lena-kross",
    "name": "Lena Kross",
    "popularity": 82,
    "momentum": 77,
    "fatigue": 15,
    "morale": 67,
    "ringSkill": 80,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-trick-williams",
    "name": "Trick Williams",
    "popularity": 81,
    "momentum": 77,
    "fatigue": 17,
    "morale": 64,
    "ringSkill": 83,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-rey-mysterio",
    "name": "Rey Mysterio",
    "popularity": 85,
    "momentum": 82,
    "fatigue": 20,
    "morale": 64,
    "ringSkill": 84,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-thunder-rosa",
    "name": "Thunder Rosa",
    "popularity": 84,
    "momentum": 81,
    "fatigue": 10,
    "morale": 70,
    "ringSkill": 84,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-lyra-valkyria",
    "name": "Lyra Valkyria",
    "popularity": 84,
    "momentum": 81,
    "fatigue": 10,
    "morale": 70,
    "ringSkill": 84,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kris-statlander",
    "name": "Kris Statlander",
    "popularity": 84,
    "momentum": 81,
    "fatigue": 10,
    "morale": 70,
    "ringSkill": 84,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-jamie-hayter",
    "name": "Jamie Hayter",
    "popularity": 84,
    "momentum": 81,
    "fatigue": 10,
    "morale": 70,
    "ringSkill": 84,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-hikaru-shida",
    "name": "Hikaru Shida",
    "popularity": 84,
    "momentum": 81,
    "fatigue": 10,
    "morale": 70,
    "ringSkill": 84,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-athena",
    "name": "Athena",
    "popularity": 84,
    "momentum": 81,
    "fatigue": 10,
    "morale": 70,
    "ringSkill": 84,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-ethan-page",
    "name": "Ethan Page",
    "popularity": 85,
    "momentum": 85,
    "fatigue": 17,
    "morale": 75,
    "ringSkill": 84,
    "promoSkill": 86,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-konosuke-takeshita",
    "name": "Konosuke Takeshita",
    "popularity": 81,
    "momentum": 77,
    "fatigue": 17,
    "morale": 64,
    "ringSkill": 83,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-carmelo-hayes",
    "name": "Carmelo Hayes",
    "popularity": 81,
    "momentum": 77,
    "fatigue": 17,
    "morale": 64,
    "ringSkill": 83,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-hangman-adam-page",
    "name": "\"Hangman\" Adam Page",
    "popularity": 81,
    "momentum": 77,
    "fatigue": 17,
    "morale": 64,
    "ringSkill": 83,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kyle-fletcher",
    "name": "Kyle Fletcher",
    "popularity": 81,
    "momentum": 77,
    "fatigue": 47,
    "morale": 64,
    "ringSkill": 83,
    "promoSkill": 88,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-shelton-benjamin",
    "name": "Shelton Benjamin",
    "popularity": 84,
    "momentum": 76,
    "fatigue": 25,
    "morale": 60,
    "ringSkill": 78,
    "promoSkill": 84,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-austin-theory",
    "name": "Austin Theory",
    "popularity": 84,
    "momentum": 76,
    "fatigue": 25,
    "morale": 60,
    "ringSkill": 78,
    "promoSkill": 84,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-adam-cole",
    "name": "Adam Cole",
    "popularity": 84,
    "momentum": 76,
    "fatigue": 55,
    "morale": 60,
    "ringSkill": 78,
    "promoSkill": 84,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-ricky-saints",
    "name": "Ricky Saints",
    "popularity": 82,
    "momentum": 79,
    "fatigue": 10,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-joe-hendry",
    "name": "Joe Hendry",
    "popularity": 82,
    "momentum": 79,
    "fatigue": 10,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-michin",
    "name": "Michin",
    "popularity": 79,
    "momentum": 76,
    "fatigue": 18,
    "morale": 72,
    "ringSkill": 80,
    "promoSkill": 90,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-the-miz",
    "name": "The Miz",
    "popularity": 82,
    "momentum": 83,
    "fatigue": 16,
    "morale": 69,
    "ringSkill": 78,
    "promoSkill": 92,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-lash-legend",
    "name": "Lash Legend",
    "popularity": 79,
    "momentum": 76,
    "fatigue": 20,
    "morale": 79,
    "ringSkill": 80,
    "promoSkill": 83,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-jordynne-grace",
    "name": "Jordynne Grace",
    "popularity": 79,
    "momentum": 76,
    "fatigue": 20,
    "morale": 79,
    "ringSkill": 80,
    "promoSkill": 83,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-r-truth",
    "name": "R-Truth",
    "popularity": 79,
    "momentum": 77,
    "fatigue": 13,
    "morale": 60,
    "ringSkill": 77,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-montez-ford",
    "name": "Montez Ford",
    "popularity": 79,
    "momentum": 77,
    "fatigue": 13,
    "morale": 60,
    "ringSkill": 77,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-jacy-jayne",
    "name": "Jacy Jayne",
    "popularity": 77,
    "momentum": 76,
    "fatigue": 16,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-kelani-jordan",
    "name": "Kelani Jordan",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 15,
    "morale": 68,
    "ringSkill": 78,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-dragon-lee",
    "name": "Dragon Lee",
    "popularity": 80,
    "momentum": 75,
    "fatigue": 13,
    "morale": 65,
    "ringSkill": 79,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-tony-d-angelo",
    "name": "Tony D'Angelo",
    "popularity": 77,
    "momentum": 75,
    "fatigue": 25,
    "morale": 75,
    "ringSkill": 76,
    "promoSkill": 83,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-jd-mcdonagh",
    "name": "JD McDonagh",
    "popularity": 77,
    "momentum": 75,
    "fatigue": 25,
    "morale": 75,
    "ringSkill": 76,
    "promoSkill": 83,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-je-von-evans",
    "name": "Je'Von Evans",
    "popularity": 76,
    "momentum": 73,
    "fatigue": 18,
    "morale": 65,
    "ringSkill": 78,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-angelo-dawkins",
    "name": "Angelo Dawkins",
    "popularity": 76,
    "momentum": 73,
    "fatigue": 18,
    "morale": 65,
    "ringSkill": 78,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-maxxine-dupri",
    "name": "Maxxine Dupri",
    "popularity": 79,
    "momentum": 77,
    "fatigue": 24,
    "morale": 77,
    "ringSkill": 76,
    "promoSkill": 85,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-lola-vice",
    "name": "Lola Vice",
    "popularity": 79,
    "momentum": 77,
    "fatigue": 24,
    "morale": 77,
    "ringSkill": 76,
    "promoSkill": 85,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-fallon-henley",
    "name": "Fallon Henley",
    "popularity": 79,
    "momentum": 77,
    "fatigue": 24,
    "morale": 77,
    "ringSkill": 76,
    "promoSkill": 85,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-blake-monroe",
    "name": "Blake Monroe",
    "popularity": 79,
    "momentum": 77,
    "fatigue": 24,
    "morale": 77,
    "ringSkill": 76,
    "promoSkill": 85,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-tank-ledger",
    "name": "Tank Ledger",
    "popularity": 80,
    "momentum": 80,
    "fatigue": 24,
    "morale": 78,
    "ringSkill": 75,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-hank-walker",
    "name": "Hank Walker",
    "popularity": 80,
    "momentum": 80,
    "fatigue": 24,
    "morale": 78,
    "ringSkill": 75,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-ivar",
    "name": "Ivar",
    "popularity": 76,
    "momentum": 75,
    "fatigue": 24,
    "morale": 78,
    "ringSkill": 75,
    "promoSkill": 80,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-sol-ruca",
    "name": "Sol Ruca",
    "popularity": 80,
    "momentum": 78,
    "fatigue": 20,
    "morale": 79,
    "ringSkill": 75,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-jaida-parker",
    "name": "Jaida Parker",
    "popularity": 80,
    "momentum": 78,
    "fatigue": 20,
    "morale": 79,
    "ringSkill": 75,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-erik",
    "name": "Erik",
    "popularity": 78,
    "momentum": 74,
    "fatigue": 19,
    "morale": 61,
    "ringSkill": 78,
    "promoSkill": 76,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-m-scara-dorada",
    "name": "Máscara Dorada",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 52,
    "morale": 74,
    "ringSkill": 78,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-noam-dar",
    "name": "Noam Dar",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 13,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-brutus-creed",
    "name": "Brutus Creed",
    "popularity": 77,
    "momentum": 76,
    "fatigue": 17,
    "morale": 69,
    "ringSkill": 74,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-luchasaurus",
    "name": "Luchasaurus",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 52,
    "morale": 74,
    "ringSkill": 78,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-hologram",
    "name": "Hologram",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 52,
    "morale": 74,
    "ringSkill": 78,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-izzi-dame",
    "name": "Izzi Dame",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 15,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-raw-ivy-nile",
    "name": "Ivy Nile",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 15,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-johnny-gargano",
    "name": "Johnny Gargano",
    "popularity": 78,
    "momentum": 80,
    "fatigue": 21,
    "morale": 78,
    "ringSkill": 76,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-the-butcher",
    "name": "The Butcher",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-the-blade",
    "name": "The Blade",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-paul-wight",
    "name": "Paul Wight",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-nick-comoroto",
    "name": "Nick Comoroto",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mike-bennett",
    "name": "Mike Bennett",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-michael-nakazawa",
    "name": "Michael Nakazawa",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-matt-sydal",
    "name": "Matt Sydal",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kip-sabian",
    "name": "Kip Sabian",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-keith-lee",
    "name": "Keith Lee",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-jeff-jarrett-w-karen-jarrett",
    "name": "Jeff Jarrett ( w/ Karen Jarrett)",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-colt-cabana",
    "name": "Colt Cabana",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-brandon-cutler",
    "name": "Brandon Cutler",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-billy-gunn",
    "name": "Billy Gunn",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-marq-quen",
    "name": "Marq Quen",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kota-ibushi",
    "name": "Kota Ibushi",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-josh-alexander",
    "name": "Josh Alexander",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-jake-doyle",
    "name": "Jake Doyle",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-dustin-rhodes",
    "name": "Dustin Rhodes",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-buddy-matthews",
    "name": "Buddy Matthews",
    "popularity": 78,
    "momentum": 76,
    "fatigue": 43,
    "morale": 62,
    "ringSkill": 75,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-yuka-sakazaki",
    "name": "Yuka Sakazaki",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 45,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-rebel",
    "name": "Rebel",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 45,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-emi-sakura",
    "name": "Emi Sakura",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 45,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-nathan-frazer",
    "name": "Nathan Frazer",
    "popularity": 76,
    "momentum": 75,
    "fatigue": 21,
    "morale": 71,
    "ringSkill": 75,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-charlie-dempsey",
    "name": "Charlie Dempsey",
    "popularity": 78,
    "momentum": 74,
    "fatigue": 25,
    "morale": 70,
    "ringSkill": 73,
    "promoSkill": 74,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-nyla-rose",
    "name": "Nyla Rose",
    "popularity": 76,
    "momentum": 76,
    "fatigue": 46,
    "morale": 72,
    "ringSkill": 75,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-smackdown-axiom",
    "name": "Axiom",
    "popularity": 78,
    "momentum": 75,
    "fatigue": 10,
    "morale": 69,
    "ringSkill": 72,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-persephone",
    "name": "Persephone",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 45,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-penelope-ford",
    "name": "Penelope Ford",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 45,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-leila-grey",
    "name": "Leila Grey",
    "popularity": 78,
    "momentum": 78,
    "fatigue": 45,
    "morale": 73,
    "ringSkill": 76,
    "promoSkill": 77,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "wwe-nxt-myles-borne",
    "name": "Myles Borne",
    "popularity": 76,
    "momentum": 75,
    "fatigue": 23,
    "morale": 71,
    "ringSkill": 77,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-kamille",
    "name": "Kamille",
    "popularity": 76,
    "momentum": 74,
    "fatigue": 14,
    "morale": 72,
    "ringSkill": 75,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-zack-gibson",
    "name": "Zack Gibson",
    "popularity": 75,
    "momentum": 72,
    "fatigue": 11,
    "morale": 60,
    "ringSkill": 72,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-wheeler-yuta",
    "name": "Wheeler Yuta",
    "popularity": 75,
    "momentum": 72,
    "fatigue": 11,
    "morale": 60,
    "ringSkill": 72,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-katsuyori-shibata",
    "name": "Katsuyori Shibata",
    "popularity": 75,
    "momentum": 72,
    "fatigue": 11,
    "morale": 60,
    "ringSkill": 72,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-daniel-garcia",
    "name": "Daniel Garcia",
    "popularity": 75,
    "momentum": 72,
    "fatigue": 11,
    "morale": 60,
    "ringSkill": 72,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-bad-apple-bryan-keith",
    "name": "Bad Apple Bryan Keith",
    "popularity": 75,
    "momentum": 72,
    "fatigue": 11,
    "morale": 60,
    "ringSkill": 72,
    "promoSkill": 75,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-wardlow",
    "name": "Wardlow",
    "popularity": 76,
    "momentum": 77,
    "fatigue": 53,
    "morale": 79,
    "ringSkill": 74,
    "promoSkill": 81,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-brian-cage",
    "name": "Brian Cage",
    "popularity": 76,
    "momentum": 77,
    "fatigue": 53,
    "morale": 79,
    "ringSkill": 74,
    "promoSkill": 81,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-satnam-singh",
    "name": "Satnam Singh",
    "popularity": 76,
    "momentum": 75,
    "fatigue": 22,
    "morale": 78,
    "ringSkill": 74,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-myron-reed",
    "name": "Myron Reed",
    "popularity": 76,
    "momentum": 75,
    "fatigue": 22,
    "morale": 78,
    "ringSkill": 74,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-lance-archer",
    "name": "Lance Archer",
    "popularity": 76,
    "momentum": 75,
    "fatigue": 22,
    "morale": 78,
    "ringSkill": 74,
    "promoSkill": 79,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-zachary-wentz",
    "name": "Zachary Wentz",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-turbo-floyd",
    "name": "Turbo Floyd",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-truth-magnum",
    "name": "Truth Magnum",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-trent-beretta",
    "name": "Trent Beretta",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-tony-nese",
    "name": "Tony Nese",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-tommy-billington",
    "name": "Tommy Billington",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-toa-liona",
    "name": "Toa Liona",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-the-beast-mortos",
    "name": "The Beast Mortos",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-shawn-dean",
    "name": "Shawn Dean",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-shane-taylor",
    "name": "Shane Taylor",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-serpentico",
    "name": "Serpentico",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-scorpio-sky",
    "name": "Scorpio Sky",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-sammy-guevara",
    "name": "Sammy Guevara",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-rush",
    "name": "Rush",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-ross-von-erich",
    "name": "Ross Von Erich",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-rocky-romero",
    "name": "Rocky Romero",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-preston-vance",
    "name": "Preston Vance",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-peter-avalon",
    "name": "Peter Avalon",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-ortiz",
    "name": "Ortiz",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-nick-wayne-w-mother-wayne",
    "name": "Nick Wayne ( w/ Mother Wayne)",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-m-stico",
    "name": "Místico",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mike-bailey",
    "name": "Mike Bailey",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-matt-menard",
    "name": "Matt Menard",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mason-madden",
    "name": "Mason Madden",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-marshall-von-erich",
    "name": "Marshall Von Erich",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mansoor",
    "name": "Mansoor",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-mvp",
    "name": "MVP",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-lee-moriarty",
    "name": "Lee Moriarty",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-lee-johnson",
    "name": "Lee Johnson",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  },
  {
    "id": "aew-aew-juice-robinson",
    "name": "Juice Robinson",
    "popularity": 74,
    "momentum": 76,
    "fatigue": 24,
    "morale": 71,
    "ringSkill": 72,
    "promoSkill": 78,
    "appearancesThisSeason": 0,
    "lastBookedWeek": 0,
    "consecutiveWeeksBooked": 0,
    "injuryStatus": "healthy",
    "injuryWeeksRemaining": 0
  }
];
