const wrestlerPortraitAliases: Record<string, string> = {
  "aew-aew-mercedes-mon": "aew-aew-mercedes-mone",
  "wwe-raw-finn-b-lor": "wwe-raw-finn-balor",
};

const availableWrestlerPortraitIds = new Set([
  "aew-aew-adam-copeland",
  "aew-aew-bobby-lashley",
  "aew-aew-cash-wheeler",
  "aew-aew-chris-jericho",
  "aew-aew-christian-cage",
  "aew-aew-darby-allin",
  "aew-aew-dax-harwood",
  "aew-aew-dr-britt-baker-d-m-d",
  "aew-aew-eddie-kingston",
  "aew-aew-jay-white",
  "aew-aew-jon-moxley",
  "aew-aew-kazuchika-okada",
  "aew-aew-kenny-omega",
  "aew-aew-kevin-knight",
  "aew-aew-kyle-o-reilly",
  "aew-aew-lena-kross",
  "aew-aew-mark-briscoe",
  "aew-aew-mark-davis",
  "aew-aew-matt-jackson",
  "aew-aew-megan-bayne",
  "aew-aew-mercedes-mone",
  "aew-aew-mjf",
  "aew-aew-nick-jackson",
  "aew-aew-orange-cassidy",
  "aew-aew-pac",
  "aew-aew-ricochet",
  "aew-aew-roderick-strong",
  "aew-aew-samoa-joe",
  "aew-aew-swerve-strickland",
  "aew-aew-thekla",
  "aew-aew-thunder-rosa",
  "aew-aew-timeless-toni-storm",
  "aew-aew-tommaso-ciampa",
  "aew-aew-will-ospreay",
  "aew-aew-willow-nightingale",
  "wwe-nxt-charlie-dempsey",
  "wwe-nxt-hank-walker",
  "wwe-nxt-izzi-dame",
  "wwe-nxt-jaida-parker",
  "wwe-nxt-kelani-jordan",
  "wwe-nxt-lola-vice",
  "wwe-nxt-myles-borne",
  "wwe-nxt-noam-dar",
  "wwe-nxt-tank-ledger",
  "wwe-nxt-tony-d-angelo",
  "wwe-raw-angelo-dawkins",
  "wwe-raw-asuka",
  "wwe-raw-austin-theory",
  "wwe-raw-bayley",
  "wwe-raw-becky-lynch",
  "wwe-raw-bron-breakker",
  "wwe-raw-bronson-reed",
  "wwe-raw-brutus-creed",
  "wwe-raw-cm-punk",
  "wwe-raw-dominik-mysterio",
  "wwe-raw-dragon-lee",
  "wwe-raw-el-grande-americano",
  "wwe-raw-erik",
  "wwe-raw-ethan-page",
  "wwe-raw-finn-balor",
  "wwe-raw-ivar",
  "wwe-raw-ivy-nile",
  "wwe-raw-iyo-sky",
  "wwe-raw-jd-mcdonagh",
  "wwe-raw-je-von-evans",
  "wwe-raw-jey-uso",
  "wwe-raw-jimmy-uso",
  "wwe-raw-joe-hendry",
  "wwe-raw-la-knight",
  "wwe-raw-liv-morgan",
  "wwe-raw-logan-paul",
  "wwe-raw-lyra-valkyria",
  "wwe-raw-maxxine-dupri",
  "wwe-raw-montez-ford",
  "wwe-raw-naomi",
  "wwe-raw-nattie",
  "wwe-raw-original-el-grande-americano",
  "wwe-raw-penta",
  "wwe-raw-raquel-rodriguez",
  "wwe-raw-rey-mysterio",
  "wwe-raw-roman-reigns",
  "wwe-raw-roxanne-perez",
  "wwe-raw-seth-rollins",
  "wwe-raw-sheamus",
  "wwe-raw-sol-ruca",
  "wwe-raw-stephanie-vaquer",
  "wwe-smackdown-alexa-bliss",
  "wwe-smackdown-axiom",
  "wwe-smackdown-bianca-belair",
  "wwe-smackdown-blake-monroe",
  "wwe-smackdown-carmelo-hayes",
  "wwe-smackdown-charlotte-flair",
  "wwe-smackdown-chelsea-green",
  "wwe-smackdown-cody-rhodes",
  "wwe-smackdown-damian-priest",
  "wwe-smackdown-drew-mcintyre",
  "wwe-smackdown-fallon-henley",
  "wwe-smackdown-giulia",
  "wwe-smackdown-gunther",
  "wwe-smackdown-ilja-dragunov",
  "wwe-smackdown-jacob-fatu",
  "wwe-smackdown-jacy-jayne",
  "wwe-smackdown-jade-cargill",
  "wwe-smackdown-johnny-gargano",
  "wwe-smackdown-jordynne-grace",
  "wwe-smackdown-kevin-owens",
  "wwe-smackdown-lash-legend",
  "wwe-smackdown-michin",
  "wwe-smackdown-nathan-frazer",
  "wwe-smackdown-nia-jax",
  "wwe-smackdown-r-truth",
  "wwe-smackdown-randy-orton",
  "wwe-smackdown-rhea-ripley",
  "wwe-smackdown-ricky-saints",
  "wwe-smackdown-sami-zayn",
  "wwe-smackdown-shinsuke-nakamura",
  "wwe-smackdown-solo-sikoa",
  "wwe-smackdown-the-miz",
  "wwe-smackdown-tiffany-stratton",
  "wwe-smackdown-trick-williams",
]);

export function getWrestlerPortraitSrc(wrestlerId: string) {
  const portraitId = wrestlerPortraitAliases[wrestlerId] ?? wrestlerId;

  if (!availableWrestlerPortraitIds.has(portraitId)) {
    return undefined;
  }

  return `/superstars/${portraitId}.png`;
}

export function hasWrestlerPortrait(wrestlerId: string) {
  return Boolean(getWrestlerPortraitSrc(wrestlerId));
}
